name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get build date (UTC+8)
        id: date
        run: |
          export TZ=Asia/Taipei
          echo "tag=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/2025cloud:${{ steps.date.outputs.tag }}
          docker build -t $IMAGE_TAG .

      - name: Push Image to Docker Hub
        run: |
          IMAGE_TAG=${{ secrets.DOCKER_USERNAME }}/2025cloud:${{ steps.date.outputs.tag }}
          docker push $IMAGE_TAG
          docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/2025cloud:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/2025cloud:latest
